# Generated by Django 2.1.15 on 2020-06-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='liked_users',
        ),
        migrations.RemoveField(
            model_name='review',
            name='liked_users',
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(max_length=1),
        ),
    ]
